site_name: Fleet Actions
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
    logo: material/bird
  features:
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      accent: orange
      primary: deep orange

      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Quickstart: getting-started/quickstart.md
      - Advanced Configuration: getting-started/advanced-configuration.md
      - Monitoring and Troubleshooting: getting-started/monitoring-troubleshooting.md
  # - Case Study: case-study.md
  - Architecture:
      - Overview: architecture/overview.md
      - Refresh: architecture/refresh.md
      - Provision: architecture/provision.md
      - Release: architecture/release.md
      - Instance: architecture/instance.md
  - Examples:
      - Basic Workflow: examples/basic-workflow.md
      - Advanced Scenarios: examples/advanced-scenarios.md
  - FAQ: faq.md
