site_name: Self-Hosted EC2 Runners for GitHub Actions
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
    logo: material/bird
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      accent: orange
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
