site_name: Fleet Actions
site_url: https://mydomain.org/mysite
theme:
  name: material
  icon:
    logo: material/bird
  features:
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      # accent: orange
      # primary: deep orange

      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: getting-started/prerequisites.md
      - Quickstart: getting-started/quickstart.md
      - Advanced Configuration: getting-started/advanced-configuration.md
      - Monitoring and Troubleshooting: getting-started/monitoring-troubleshooting.md
  # - Case Study: case-study.md
  - Architecture:
      - Overview: architecture/overview.md
      - Provision:
          - Overview: architecture/provision/provision.md
          - Selection:
              - Pickup Manager: architecture/provision/selection/pickup-manager.md
              - Claim Workers: architecture/provision/selection/claim-workers.md
          - Creation:
              - Fleet Creation: architecture/provision/creation/fleet-creation.md
              - Fleet Validation: architecture/provision/creation/fleet-validation.md
          - Post Provision: architecture/provision/post-provision.md
      - Release: architecture/release.md
      - Refresh: architecture/refresh.md
      - Others:
          - Instance Bootstrap: architecture/instance-initialization.md
          - Resource Pool: architecture/resource-pool.md
  - Examples:
      - Basic Workflow: examples/basic-workflow.md
      - Advanced Scenarios: examples/advanced-scenarios.md
