name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  # Once all tests have been completed,
  # Run the local actions

  test-action-echo:
    name: local action mode - echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: test
        id: test-action
        uses: ./
        with:
          mode: echo
          echo: 'Hello there! General Kenobi!!'
          table-name: 'test-table'
          aws-region: 'test-region'
        env:
          # https://github.com/actions/toolkit/blob/master/docs/action-debugging.md
          ACTIONS_STEP_DEBUG: true
